apiVersion: v1
kind: Service
metadata:
  name: nodeportappsvc
spec:
  type: NodePort
  selector:
    app: nodeportapp 
  ports:
    - nodePort: 32767 
      port: 8888
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeportapplication
spec:
  selector:
    matchLabels:
      app: nodeportapp
  replicas: 5
  template:
    metadata:
      labels:
        app: nodeportapp 
    spec:
      containers:
      - name: frontend
        image: docker.io/justsanjeev/nginx-oss:latest
        ports:
          - name: http
            containerPort: 80

