kind: Service
apiVersion: v1
metadata:
  name: rp-frontend-service
spec:
  type: NodePort
  selector:
    app: rp-frontend
  ports:
    - nodePort: 32100
      port: 8080
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-dployment
spec:
  selector:
    matchLabels:
      app: rp-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: rp-frontend
    spec:
      containers:
        - name: apps-frontend
          image: docker.io/justsanjeev/rp-nginx:latest
          ports:
            - name: http
              containerPort: 80
