apiVersion: v1
kind: Service
metadata:
  name: sportssvc
spec:
  selector:
    app: sports-app
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8885
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
spec:
  selector:
    matchLabels:
      app: sports-app
  replicas: 5
  template:
    metadata:
      labels:
        app: sports-app
    spec:
      containers:
        - name: wsgi-flask-sports
          image: docker.io/justsanjeev/wsgi-flask-sports:latest
          ports:
            - name: http
              containerPort: 80

