apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-flask-application
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-flask-application
        tier: backend
        track: stable
    spec:
      containers:
        - name: flask-container
          image: nginx
          ports:
            - name: http
              containerPort: 80

